version: '3.3'

services:
  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=patients
      - POSTGRES_PASSWORD=patients
      - POSTGRES_DB=patients
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
